[package]
name = "seed-search"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.diesel]
version = "1.4.6"
default-features = false
features = ["sqlite", "serde_json"]