CREATE TABLE fun (
    id INTEGER PRIMARY KEY NOT NULL,
    "name" TEXT
);

INSERT INTO
    fun (name)
VALUES
    ('Singing Sword'),
    ('mace of Variability'),
    ('staff of Olgreb'),
    ('Vampire''s Tooth'),
    ('sceptre of Torment'),
    ('sword of Zonguldrok'),
    ('faerie dragon scales'),
    ('demon blade "Leech"'),
    ('dagger "Morg"'),
    ('longbow "Zephyr"'),
    ('giant club "Skullcrusher"'),
    ('glaive of the Guard'),
    ('zealot''s sword'),
    ('arbalest "Damnation"'),
    ('morningstar "Eos"'),
    ('trident of the Octopus King'),
    ('mithril axe "Arga"'),
    ('Elemental Staff'),
    ('heavy crossbow "Sniper"'),
    ('lance "Wyrmbane"'),
    ('Spriggan''s Knife'),
    ('plutonium sword'),
    ('great mace "Undeadhunter"'),
    ('storm bow'),
    ('cloak of the Thief'),
    ('hood of the Assassin'),
    ('skin of Zhor'),
    ('salamander hide armour'),
    ('gauntlets of War'),
    ('shield of Resistance'),
    ('Maxwell''s patent armour'),
    ('mask of the Dragon'),
    ('robe of Night'),
    ('scales of the Dragon King'),
    ('hat of the Alchemist'),
    ('cloak of Starlight'),
    ('shield of the Gong'),
    ('amulet of the Air'),
    ('ring of Shadows'),
    ('amulet of the Four Winds'),
    ('necklace of Bloodlust'),
    ('ring of the Hare'),
    ('ring of the Tortoise'),
    ('ring of the Mage'),
    ('brooch of Shielding'),
    ('robe of Clouds'),
    ('hat of Pondering'),
    ('obsidian axe'),
    ('lightning scales'),
    ('Black Knight''s barding'),
    ('autumn katana'),
    ('shillelagh "Devastator"'),
    ('dragonskin cloak'),
    ('ring of the Octopus King'),
    ('moon troll leather armour'),
    ('dark maul'),
    ('hat of the High Council'),
    ('arc blade'),
    ('lajatang of Order'),
    ('great mace "Firestarter"'),
    ('orange crystal plate armour'),
    ('Majin-Bo'),
    ('pair of quick blades "Gyre" and "Gimble"'),
    ('robe of Vines'),
    ('frozen axe "Frostbite"'),
    ('warlock''s mirror'),
    ('Maxwell''s thermic engine'),
    ('demon trident "Rift"'),
    ('staff of Battle'),
    ('Cigotuvi''s embrace'),
    ('seven-league boots');

CREATE TABLE weapons (
    id INTEGER PRIMARY KEY NOT NULL,
    "name" TEXT
);

INSERT INTO
    weapons (name)
VALUES
    ('Singing Sword'),
    ('mace of Variability'),
    ('staff of Olgreb'),
    ('Vampire''s Tooth'),
    ('sceptre of Torment'),
    ('sword of Zonguldrok'),
    ('demon blade "Leech"'),
    ('dagger "Morg"'),
    ('longbow "Zephyr"'),
    ('giant club "Skullcrusher"'),
    ('glaive of the Guard'),
    ('zealot''s sword'),
    ('arbalest "Damnation"'),
    ('morningstar "Eos"'),
    ('mithril axe "Arga"'),
    ('Elemental Staff'),
    ('heavy crossbow "Sniper"'),
    ('lance "Wyrmbane"'),
    ('Spriggan''s Knife'),
    ('plutonium sword'),
    ('great mace "Undeadhunter"'),
    ('storm bow'),
    ('gauntlets of War'),
    ('shield of Resistance'),
    ('mask of the Dragon'),
    ('robe of Night'),
    ('scales of the Dragon King'),
    ('hat of the Alchemist'),
    ('cloak of Starlight'),
    ('shield of the Gong'),
    ('necklace of Bloodlust'),
    ('obsidian axe'),
    ('autumn katana'),
    ('shillelagh "Devastator"'),
    ('dark maul'),
    ('arc blade'),
    ('great mace "Firestarter"'),
    ('Majin-Bo'),
    ('pair of quick blades "Gyre" and "Gimble"'),
    ('frozen axe "Frostbite"'),
    ('Maxwell''s thermic engine'),
    ('demon trident "Rift"'),
    ('staff of Battle');