CREATE TABLE seed (
    id INTEGER PRIMARY KEY,
    version TEXT NOT NULL
);

CREATE TABLE item (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    class TEXT NOT NULL,
    subtype TEXT NOT NULL,
    ego TEXT,
    ac INTEGER,
    accuracy INTEGER,
    damage INTEGER,
    delay INTEGER,
    encumbrance INTEGER,
    plus INTEGER,
    weap_skill TEXT,
    artefact BOOLEAN,
    unrand BOOLEAN
);

CREATE TABLE artprops (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    value INTEGER NOT NULL,
    item_id INTEGER NOT NULL REFERENCES item(id)
);

CREATE TABLE level (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL
);

CREATE TABLE item_seen (
    id INTEGER PRIMARY KEY,
    item_id INTEGER NOT NULL REFERENCES item(id),
    level_id INTEGER NOT NULL REFERENCES level(id),
    seed_id INTEGER NOT NULL REFERENCES seed(id)
);

INSERT INTO
    level (name)
VALUES
    ("Temple"),
    ("D:1"),
    ("D:2"),
    ("D:3"),
    ("D:4"),
    ("D:5"),
    ("D:6"),
    ("D:7"),
    ("D:8"),
    ("D:9"),
    ("D:10"),
    ("D:11"),
    ("D:12"),
    ("D:13"),
    ("D:14"),
    ("D:15"),
    ("Lair:1"),
    ("Lair:2"),
    ("Lair:3"),
    ("Lair:4"),
    ("Lair:5"),
    ("Lair:6"),
    ("Orc:1"),
    ("Orc:2"),
    ("Spider:1"),
    ("Spider:2"),
    ("Spider:3"),
    ("Spider:4"),
    ("Snake:1"),
    ("Snake:2"),
    ("Snake:3"),
    ("Snake:4"),
    ("Shoals:1"),
    ("Shoals:2"),
    ("Shoals:3"),
    ("Shoals:4"),
    ("Swamp:1"),
    ("Swamp:2"),
    ("Swamp:3"),
    ("Swamp:4"),
    ("Vaults:1"),
    ("Vaults:2"),
    ("Vaults:3"),
    ("Vaults:4"),
    ("Vaults:5"),
    ("Crypt:1"),
    ("Crypt:2"),
    ("Crypt:3"),
    ("Depths:1"),
    ("Depths:2"),
    ("Depths:3"),
    ("Depths:4"),
    ("Depths:5"),
    ("Hell"),
    ("Elf:1"),
    ("Elf:2"),
    ("Elf:3"),
    ("Zot:1"),
    ("Zot:2"),
    ("Zot:3"),
    ("Zot:4"),
    ("Zot:5"),
    ("Slime:1"),
    ("Slime:2"),
    ("Slime:3"),
    ("Slime:4"),
    ("Slime:5"),
    ("Tomb:1"),
    ("Tomb:2"),
    ("Tomb:3"),
    ("Tar:1"),
    ("Tar:2"),
    ("Tar:3"),
    ("Tar:4"),
    ("Tar:5"),
    ("Tar:6"),
    ("Tar:7"),
    ("Coc:1"),
    ("Coc:2"),
    ("Coc:3"),
    ("Coc:4"),
    ("Coc:5"),
    ("Coc:6"),
    ("Coc:7"),
    ("Dis:1"),
    ("Dis:2"),
    ("Dis:3"),
    ("Dis:4"),
    ("Dis:5"),
    ("Dis:6"),
    ("Dis:7"),
    ("Geh:1"),
    ("Geh:2"),
    ("Geh:3"),
    ("Geh:4"),
    ("Geh:5"),
    ("Geh:6"),
    ("Geh:7");